---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-database-core
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-networking-core
    namespace: flux-system
  - name: infra-storage-csi-driver-nfs
    namespace: flux-system
  interval: 15m0s
  path: ./infrastructure/subsystems/database-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-database-core
    namespace: flux-system
  timeout: 2m0s
  wait: true
