---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- root.yaml
- infra-clusterops-core.yaml
- infra-kubernetes-core.yaml
- infra-networking-core.yaml
- infra-security-core.yaml
- infra-security-outpost.yaml
- infra-storage-csi-driver-nfs.yaml
- infra-storage-core-minio.yaml
- apps-bitwarden.yaml
- infra-database-core.yaml
- apps-harbor.yaml
- config-storage.yaml
- policy-baseline-pss.yaml
- policy-best-practices.yaml
